backend:
  name: github
  repo: AlleyCorpNord/acn-radar
  branch: main
  auth_endpoint: auth
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - label: "Blip"
    name: "blip"
    folder: "src/content/blips"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Opinion", name: "opinion", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Ring",
          name: "ring",
          widget: "select",
          options:
            [
              { label: "Adopt", value: "adopt" },
              { label: "Trial", value: "trial" },
              { label: "Assess", value: "assess" },
              { label: "Hold", value: "hold" },
            ],
        }
      - {
          label: "Quadrant",
          name: "quadrant",
          widget: "select",
          options:
            [
              {
                label: "Languages/Frameworks",
                value: "languages-and-frameworks",
              },
              { label: "Techniques", value: "techniques" },
              { label: "Platforms", value: "platforms" },
              { label: "Tools", value: "tools" },
            ],
        }
      - {
          label: "Business Model",
          name: "businessModel",
          widget: "select",
          multiple: true,
          required: false,
          options:
            [
              { label: "Open Source", value: "open-source" },
              { label: "Free Tier", value: "free-tier" },
              { label: "Start Up program", value: "start-up-program" },
              { label: "SaaS", value: "saas" },
              { label: "On Premise", value: "on-premise" },
            ],
        }
      - {
          label: "Projects",
          name: "projectIds",
          widget: "relation",
          collection: "project",
          multiple: true,
          value_field: "{{slug}}",
          display_fields: ["{{title}}"],
          search_fields: ["title"],
        }
  - label: "Project"
    name: "project"
    folder: "src/content/projects"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Link", name: "link", widget: "string", required: false }
      - {
          label: "Contacts",
          name: "contacts",
          widget: "markdown",
          required: false,
          default: " - [Contact Name]"
        }
