backend:
  name: github
  repo: AlleyCorpNord/acn-radar
  branch: redesign # Branch to update (optional; defaults to master)
  auth_endpoint: auth
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - label: "Blips"
    name: "blips"
    folder: "src/content/blips"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Opinion", name: "opinion", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Ring",
          name: "ring",
          widget: "select",
          options:
            [
              { label: "Adopt", value: "adopt" },
              { label: "Trial", value: "trial" },
              { label: "Assess", value: "assess" },
              { label: "Hold", value: "hold" },
            ],
        }
      - {
          label: "Quadrant",
          name: "quadrant",
          widget: "select",
          options:
            [
              {
                label: "Languages & Frameworks",
                value: "languages-and-frameworks",
              },
              { label: "Techniques", value: "techniques" },
              { label: "Platforms", value: "platforms" },
              { label: "tools", value: "Tools" },
            ],
        }
      - { label: "License", name: "license", widget: "text" }
      - {
          label: "Projects",
          name: "projects",
          widget: "relation",
          collection: "projects",
          multiple: true,
          value_field: "slug",
          search_fields: ["title"],
        }
  - label: "Projects"
    name: "projects"
    folder: "src/content/projects"
    slug: "{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
